# Generated by Django 2.2.4 on 2019-09-26 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название фрагмента урока', max_length=1000)),
                ('description', models.TextField(help_text='Описание педагогического приёма')),
            ],
            options={
                'verbose_name': 'Фрагмент урока',
                'verbose_name_plural': 'Фрагменты урока',
            },
        ),
        migrations.CreateModel(
            name='TeachingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальное ID для данного метода', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название педагогического приёма', max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание педагогического приёма', verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qrmethods.LessonPart', verbose_name='Фрагмент урока')),
            ],
            options={
                'verbose_name': 'Метод обучения',
                'verbose_name_plural': 'Методы обучения',
            },
        ),
    ]
