# Generated by Django 2.2.4 on 2019-09-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmethods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpart',
            name='url',
            field=models.CharField(default=None, help_text='Ссылка на раздел', max_length=500),
            preserve_default=False,
        ),
    ]
