# Generated by Django 2.2.4 on 2019-09-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmethods', '0002_lessonpart_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpart',
            name='description',
            field=models.TextField(help_text='Описание раздела'),
        ),
        migrations.AlterField(
            model_name='lessonpart',
            name='name',
            field=models.CharField(help_text='Название раздела', max_length=1000),
        ),
    ]
